services: 
  api:
    container_name: url-shortner-api
    build: api/
    depends_on:
      db: 
        condition: service_healthy
        restart: true
    env_file:
      - ".env"
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - url-shortner-network
  redis:
    container_name: url-shortner-redis
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - url-shortner-network
  db:
    container_name: url-shortner-db
    image: postgres:18
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - url-shortner-network
  proxy:
    container_name: url-shortner-nginx
    image: nginx:latest
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - url-shortner-network
    ports:
      - 80:80

  web:
    build:
      web/
    networks:
      - url-shortner-network
    expose:
      - "${WEB_PORT}"
    environment:
      - APP_PORT=${WEB_PORT}
networks:
  url-shortner-network:
    driver: bridge